format = """
[ ](bg:white)\
$os\
[](fg:white bg:blue )\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:bright-green)\
$line_break$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
style_user = "bg:green"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:white fg:black"
disabled = false # Disabled by default
format = '[$symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon  = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "bg:blue bold"
format = "[   $path ]($style)"
truncate_to_repo=true
truncation_length = 3
truncation_symbol = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "
[git_branch]
symbol = ""
style = "bg:bright-green fg:black bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:bright-green fg:black bold"
format = '[$all_status$ahead_behind ]($style)'

