#!/bin/bash
# Kills a process that uses a specified port on macOS
# Usage "./kpp 1337"
script="${0##*/}"
if [[ $1 == "-h" || $1 == "--help" ]];
then
    echo "Kills a process that uses a specified port on macOS"
    echo "Usage:   $script <PORT>"
    echo "Example: $script 1337"
else
    pid=$(sudo lsof -i:$1 -P | grep LISTEN | sudo awk '{print $2}')
    if [[ $pid ]]
    then
        sudo kill -9 --verbose $pid && echo "Killed process $pid"
    else
        echo "Port is not used by a process"
    fi
fi
