#import = ["/home/acelakov/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
import = ["/home/acelakov/.config/alacritty/dracula.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNL NF"

[window]
opacity = 0.98
